#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr &
nitrogen --set-scaled ~/pictures/milky-way-2695569__480.jpg

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width    0
bspc config window_gap      0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
$HOME/.config/polybar/launch.sh &
